# Generated by Django 3.2 on 2021-09-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210827_0826"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
