# Generated by Django 3.2 on 2022-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211117_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationcampaign',
            name='annotation_scope',
            field=models.IntegerField(choices=[(1, 'Rectangle'), (2, 'Whole')], default=1),
        ),
    ]
