# Generated by Django 3.2 on 2022-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_annotationcampaign_annotation_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationcampaign",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="instructions_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationcampaign",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationset",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtask",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Created"), (1, "Started"), (2, "Finished")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
