# Generated by Django 3.2 on 2022-01-27 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_add_blanks_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="annotators",
            field=models.ManyToManyField(
                related_name="task_campaigns",
                through="api.AnnotationTask",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
