# Generated by Django 3.2 on 2022-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_annotationcampaign_annotators"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="collections",
            field=models.ManyToManyField(
                related_name="datasets",
                to="api.Collection",
            ),
        ),
        migrations.DeleteModel(
            name="CollectionDataset",
        ),
    ]
