# Generated by Django 3.2.16 on 2023-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_useless_collectiondataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectroconfig",
            name="hp_filter_min_freq",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="colormap",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="data_normalization",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="dynamic_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="dynamic_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="frequency_resolution",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="spectro_normalization",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_0",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_3",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_4",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_5",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_6",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_7",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="time_resolution_zoom_8",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="zscore_duration",
            field=models.IntegerField(null=True),
        ),
    ]
