# Generated by Django 3.2.16 on 2023-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20230418_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectroconfig",
            name="hp_filter_min_freq",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="colormap",
            field=models.CharField(default="blues", max_length=255),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="data_normalization",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="dynamic_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="dynamic_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="frequency_resolution",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="spectro_normalization",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="zscore_duration",
            field=models.IntegerField(default=0),
        ),
    ]
