# Generated by Django 3.2.16 on 2023-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_auto_20230423_1909"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiometadatum",
            old_name="sample_rate_khz",
            new_name="dataset_sr",
        ),
        migrations.RenameField(
            model_name="audiometadatum",
            old_name="num_channels",
            new_name="channel_count",
        ),
    ]
