# Generated by Django 3.2.16 on 2023-04-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20230428_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectroconfig",
            name="data_normalization",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="spectro_normalization",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="zscore_duration",
            field=models.CharField(max_length=255),
        ),
    ]
