# Generated by Django 3.2.16 on 2023-05-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_annotationtask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255)),
                ('annotation_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_comments', to='api.annotationtask')),
                ('dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.datasetfile')),
            ],
        ),
    ]
