# Generated by Django 3.2.16 on 2023-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_annotationtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectroconfig",
            name="frequency_resolution",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_0",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_1",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_2",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_3",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_4",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_5",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_6",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_7",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="spectroconfig",
            name="time_resolution_zoom_8",
            field=models.FloatField(default=0),
        ),
    ]
