# Generated by Django 3.2.16 on 2023-09-06 09:14

from django.db import migrations, models

# See https://docs.djangoproject.com/en/3.2/topics/migrations/#data-migrations
def remove_unnasigned(apps, schema_editor):
    AnnotationTask = apps.get_model("api", "AnnotationTask")
    AnnotationTask.objects.filter(status=3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20230504_1019"),
    ]

    operations = [
        migrations.RunPython(remove_unnasigned),
        migrations.AlterField(
            model_name="annotationtask",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Created"), (1, "Started"), (2, "Finished")], default=0
            ),
        ),
    ]
