# Generated by Django 3.2.21 on 2023-09-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230504_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceIndicatorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'confidence_sets',
            },
        ),
        migrations.CreateModel(
            name='ConfidenceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('level', models.IntegerField()),
                ('confidence_indicator_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_indicators', to='api.confidenceindicatorset')),
                ('default_confidence_indicator_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_confidence_indicator', to='api.confidenceindicatorset')),
            ],
            options={
                'db_table': 'confidence_indicator',
            },
        ),
        migrations.AddField(
            model_name='annotationcampaign',
            name='confidence_indicator_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.confidenceindicatorset'),
        ),
        migrations.AddField(
            model_name='annotationresult',
            name='confidence_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.confidenceindicator'),
        ),
    ]
