# Generated by Django 3.2.16 on 2023-05-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20230504_1019"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.CharField(max_length=255)),
                (
                    "annotation_task",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_comments",
                        to="api.annotationtask",
                    ),
                ),
                (
                    "annotation_result",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.datasetfile",
                    ),
                ),
            ],
        ),
    ]
