# Generated by Django 3.2.16 on 2023-05-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0020_annotationcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="api.annotationtask",
            ),
        ),
    ]
