# Generated by Django 3.2.21 on 2023-09-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_change_zoom_level_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=255)),
                (
                    "annotation_result",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_comments",
                        to="api.annotationresult",
                    ),
                ),
                (
                    "annotation_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="api.annotationtask",
                    ),
                ),
            ],
            options={
                "db_table": "annotation_comment",
            },
        ),
    ]
