# Generated by Django 3.2.21 on 2023-09-24 17:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_change_zoom_level_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
