# Generated by Django 3.2.21 on 2023-10-17 13:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_change_zoom_level_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("body", tinymce.models.HTMLField()),
                ("date", models.DateField(blank=True, null=True)),
                ("vignette", models.URLField(default="")),
            ],
            options={
                "verbose_name_plural": "news",
                "db_table": "news",
            },
        ),
    ]
