# Generated by Django 3.2.21 on 2023-11-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_annotationcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='spectro_configs',
        ),
        migrations.AddField(
            model_name='spectroconfig',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectro_configs', to='api.dataset'),
        ),
    ]
