# Generated by Django 3.2.19 on 2023-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_annotationcomment_annotation_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationcomment",
            old_name="comments",
            new_name="comment",
        ),
    ]
