# Generated by Django 3.2.16 on 2023-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_annotationcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationcampaign",
            options={"ordering": ["name", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dataset",
            options={"ordering": ["name", "created_at"]},
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
