# Generated by Django 3.2.21 on 2023-11-10 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_annotationcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationcampaign',
            options={'ordering': ['name', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name', 'created_at']},
        ),
        migrations.AddField(
            model_name='annotationcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
        ),
    ]
