# Generated by Django 3.2.21 on 2023-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="intro",
            field=models.CharField(max_length=255),
        ),
    ]
