# Generated by Django 3.2.23 on 2023-11-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfidenceIndicatorSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "confidence_sets",
            },
        ),
        migrations.CreateModel(
            name="ConfidenceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, unique=True)),
                ("level", models.IntegerField()),
                ("is_default", models.BooleanField(default=False)),
                (
                    "confidence_indicator_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidence_indicators",
                        to="api.confidenceindicatorset",
                        verbose_name="Included in this set :",
                    ),
                ),
            ],
            options={
                "db_table": "confidence_indicator",
            },
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="confidence_indicator_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.confidenceindicatorset",
            ),
        ),
        migrations.AddField(
            model_name="annotationresult",
            name="confidence_indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.confidenceindicator",
            ),
        ),
    ]
