# Generated by Django 3.2.21 on 2023-11-08 14:21

from django.db import migrations

def update_spectro_config(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('yourappname', 'Person')
    for person in Person.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20231108_1200'),
    ]

    operations = [
        migrations.RunPython(update_spectro_config)
    ]
