# Generated by Django 3.2.23 on 2023-11-16 13:57

from django.db import migrations, models
import django.db.models.deletion

from backend.api.models import SaveDatasetSpectroConfig, Dataset


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_news"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataset",
            old_name="spectro_configs",
            new_name="old_spectro_configs",
        ),
        migrations.AlterField(
            model_name='dataset',
            name='old_spectro_configs',
            field=models.ManyToManyField(related_name='old_datasets', to='api.SpectroConfig'),
        ),
        migrations.AddField(
            model_name="spectroconfig",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spectro_configs",
                to="api.dataset",
            ),
        ),
        migrations.CreateModel(
            name="SaveDatasetSpectroConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_save",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="save_spectro_configs",
                        to="api.dataset",
                    ),
                ),
                (
                    "spectro_configs_save",
                    models.ManyToManyField(
                        related_name="save_datasets", to="api.SpectroConfig"
                    ),
                ),
            ],
        ),
    ]
