# Generated by Django 3.2.21 on 2023-11-10 16:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_news"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationcampaign",
            options={"ordering": ["name", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dataset",
            options={"ordering": ["name", "created_at"]},
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
