# Generated by Django 3.2.23 on 2023-11-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_created_at_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectroconfig",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.dataset",
            ),
        ),
        migrations.AlterField(
            model_name='spectroconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
