# Generated by Django 3.2.23 on 2023-11-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_confidence_indicator_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-date"], "verbose_name_plural": "news"},
        ),
    ]
