# Generated by Django 3.2.23 on 2023-11-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_news_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetFilePrecalculatedAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("start_frequency", models.FloatField(blank=True, null=True)),
                ("end_frequency", models.FloatField(blank=True, null=True)),
                ("algorithm", models.CharField(max_length=255)),
                ("is_box", models.BooleanField(default=True)),
                ("confidence_level", models.FloatField(blank=True, null=True)),
                (
                    "annotation_tag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.annotationtag",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precalculated_annotations",
                        to="api.datasetfile",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_file_precalculated_annotation",
            },
        ),
    ]
