# Generated by Django 3.2.23 on 2023-11-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_datasetfileprecalculatedannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetfileprecalculatedannotation",
            name="annotation_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
