# Generated by Django 3.2.23 on 2023-11-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
        ("osmosewebsite", "0007_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
