# Generated by Django 3.2.23 on 2023-12-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationcampaign",
            name="confidence_indicator_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.confidenceindicatorset",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="datasets", to="api.Collection"
            ),
        ),
    ]
