# Generated by Django 3.2.23 on 2023-11-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
        ("api", "0031_datasetfileprecalculatedannotation_annotation_label"),
    ]

    operations = []
