# Generated by Django 3.2.23 on 2024-01-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_allow_blank_collections_confidence_set'),
        ('api', '0031_delete_news'),
    ]

    operations = [
    ]
