# Generated by Django 3.2.23 on 2024-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_merge_20240108_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("parameters", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
