# Generated by Django 3.2.23 on 2024-02-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_detector"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="usage",
            field=models.IntegerField(choices=[(1, "Create"), (2, "Check")], default=1),
        ),
        migrations.AddField(
            model_name="annotationresult",
            name="is_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotationtask",
            name="detector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_tasks",
                to="api.detector",
            ),
        ),
    ]
