# Generated by Django 3.2.23 on 2024-04-03 12:11
""" Linked to ADEV-63 ticket"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_annotationresult_dataset_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationTag",
            new_name="Label",
        ),
        migrations.AlterModelTable(
            name="label",
            table=None,
        ),
        migrations.RenameField(
            model_name="annotationresult",
            old_name="annotation_tag",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="annotationset",
            old_name="tags",
            new_name="labels",
        ),
    ]
