# Generated by Django 3.2.23 on 2024-04-05 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_alter_annotationresult_dataset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationCampaignArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotationcampaign',
            name='archive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to='api.annotationcampaignarchive'),
        ),
    ]
