# Generated by Django 3.2.23 on 2024-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_campaign_archivage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationcampaignarchive',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
