# Generated by Django 3.2.23 on 2024-04-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_rename_tag_label"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationSet",
            new_name="LabelSet",
        ),
        migrations.RenameField(
            model_name="annotationcampaign",
            old_name="annotation_set",
            new_name="label_set",
        ),
        migrations.AlterModelTable(
            name="labelset",
            table=None,
        ),
    ]
