# Generated by Django 3.2.23 on 2024-04-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_annotationcampaignarchive_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationcampaign",
            old_name="end",
            new_name="deadline",
        ),
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="start",
        ),
    ]
