# Generated by Django 3.2.25 on 2024-04-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_annotationset_labelset'),
        ('api', '0037_replace_campaign_start-end_by_deadline'),
    ]

    operations = [
    ]
