# Generated by Django 3.2.23 on 2024-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_update_spectro_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectroconfig",
            name="zscore_duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
