# Generated by Django 3.2.23 on 2024-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_spectroconfig_zscore_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiometadatum",
            name="audio_file_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
