# Generated by Django 3.2.23 on 2024-04-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_audiometadatum_audio_file_dataset_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectroconfig",
            name="number_spectra",
        ),
    ]
