# Generated by Django 3.2.25 on 2024-07-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_remove_spectroconfig_number_spectra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationcampaign",
            options={"ordering": ["name"]},
        ),
    ]
