# Generated by Django 3.2.25 on 2024-07-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_annotationcampaign_options"),
        ("api", "0044_alter_dataset_dataset_type"),
    ]

    operations = []
