# Generated by Django 3.2.25 on 2024-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_multilinearscale_inner_scales"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="spectrogramconfiguration",
            name="api_spectrogramconfiguration_name_dataset_unicity_constraint",
        ),
        migrations.AddConstraint(
            model_name="spectrogramconfiguration",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "dataset_id",
                    "linear_frequency_scale_id",
                    "multi_linear_frequency_scale_id",
                ),
                name="api_spectrogramconfiguration_name_dataset_unicity_constraint",
            ),
        ),
    ]
