# Generated by Django 3.2.25 on 2024-07-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_merge_20240701_0956"),
        ("api", "0047_auto_20240703_1515"),
    ]

    operations = []
