# Generated by Django 3.2.25 on 2024-09-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_merge_20240723_1122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationtask",
            options={"ordering": ["dataset_file__audio_metadatum__start"]},
        ),
    ]
