# Generated by Django 3.2.25 on 2024-09-30 14:59

from django.db import migrations, models

from backend.api.models import AnnotationTask


def update_status(apps, schema_editor):
    task: AnnotationTask = apps.get_model("api", "AnnotationTask")
    task.objects.filter(status=0).update(status_new="C")
    task.objects.filter(status=1).update(status_new="S")
    task.objects.filter(status=2).update(status_new="F")


def reverse_update_status(apps, schema_editor):
    task: AnnotationTask = apps.get_model("api", "AnnotationTask")
    task.objects.filter(status_new="C").update(status=0)
    task.objects.filter(status_new="S").update(status=1)
    task.objects.filter(status_new="F").update(status=2)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_alter_annotationtask_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtask",
            name="status_new",
            field=models.TextField(
                choices=[("C", "Created"), ("S", "Started"), ("F", "Finished")],
                default="C",
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(update_status, reverse_update_status),
    ]
