# Generated by Django 3.2.25 on 2024-10-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_clean_duplicated_tasks"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotationfilerange",
            unique_together={
                (
                    "first_file_index",
                    "last_file_index",
                    "annotation_campaign",
                    "annotator",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="annotationtask",
            unique_together={("dataset_file", "annotation_campaign", "annotator")},
        ),
    ]
