# Generated by Django 3.2.25 on 2024-10-09 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_add_task_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationcampaign",
            name="datasets",
            field=models.ManyToManyField(
                related_name="annotation_campaigns", to="api.Dataset"
            ),
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="first_file_index",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="last_file_index",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
