# Generated by Django 3.2.25 on 2024-10-09 10:23

from django.db import migrations, models

from backend.api.models import AnnotationFileRange


def update_files_count(apps, schema_editor):
    file_range: AnnotationFileRange = apps.get_model("api", "AnnotationFileRange")
    for r in file_range.objects.all():
        r.files_count = r.last_file_index - r.first_file_index + 1
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_auto_20241009_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationfilerange",
            name="files_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_files_count, reverse_code=migrations.RunPython.noop
        ),
    ]
