# Generated by Django 3.2.25 on 2024-10-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from backend.api.models import AnnotationComment, AnnotationTask


def update_comments(apps, schema_editor):
    comment_model: AnnotationComment.__class__ = apps.get_model(
        "api", "AnnotationComment"
    )
    for comment in comment_model.objects.all():
        comment.annotation_campaign_id = comment.annotation_task.annotation_campaign_id
        comment.author_id = comment.annotation_task.annotator_id
        comment.dataset_file_id = comment.annotation_task.dataset_file_id
        comment.save()


def reverse_update_comments(apps, schema_editor):
    comment_model: AnnotationComment.__class__ = apps.get_model(
        "api", "AnnotationComment"
    )
    task_model: AnnotationTask.__class__ = apps.get_model("api", "AnnotationTask")
    for comment in comment_model.objects.all():
        task = task_model.objects.filter(
            annotation_campaign_id=comment.annotation_campaign_id,
            annotator_id=comment.author_id,
            dataset_file_id=comment.dataset_file_id,
        )
        if task.exists():
            task = task.first()
        else:
            task = task_model.objects.create(
                annotation_campaign_id=comment.annotation_campaign_id,
                annotator_id=comment.author_id,
                dataset_file_id=comment.dataset_file_id,
            )
        comment.annotation_task = task
        comment.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0059_annotationfilerange_files_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="annotators",
        ),
        # Add nullable fields
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation_task",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="api.annotationtask",
            ),
        ),
        migrations.AddField(
            model_name="annotationcomment",
            name="annotation_campaign",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.annotationcampaign",
            ),
        ),
        migrations.AddField(
            model_name="annotationcomment",
            name="author",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auth.user",
            ),
        ),
        migrations.AddField(
            model_name="annotationcomment",
            name="dataset_file",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.datasetfile",
            ),
        ),
        # Migrate info
        migrations.RunPython(update_comments, reverse_update_comments),
        # Clean
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation_campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.annotationcampaign",
            ),
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auth.user",
            ),
        ),
        migrations.AlterField(
            model_name="annotationcomment",
            name="dataset_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.datasetfile",
            ),
        ),
        migrations.RemoveField(
            model_name="annotationcomment",
            name="annotation_task",
        ),
    ]
