# Generated by Django 3.2.25 on 2024-10-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_update_annotation_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationcomment",
            name="annotation_result",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.annotationresult",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotationfilerange",
            unique_together=set(),
        ),
    ]
