# Generated by Django 3.2.25 on 2024-10-29 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0062_auto_20241025_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="annotators",
            field=models.ManyToManyField(
                related_name="campaigns",
                through="api.AnnotationFileRange",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
