# Generated by Django 3.2.25 on 2024-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_annotationcampaign_annotators"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="labels_with_acoustic_features",
            field=models.ManyToManyField(blank=True, to="api.Label"),
        ),
    ]
