# Generated by Django 3.2.25 on 2024-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_annotationcampaign_labels_with_acoustic_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationResultAcousticFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_frequency",
                    models.FloatField(
                        blank=True,
                        help_text="[Hz] Frequency at the beginning of the signal",
                        null=True,
                    ),
                ),
                (
                    "end_frequency",
                    models.FloatField(
                        blank=True,
                        help_text="[Hz] Frequency at the end of the signal",
                        null=True,
                    ),
                ),
                (
                    "min_frequency",
                    models.IntegerField(
                        blank=True,
                        help_text="[Hz] Minimum frequency of the signal",
                        null=True,
                    ),
                ),
                (
                    "max_frequency",
                    models.IntegerField(
                        blank=True,
                        help_text="[Hz] Maximum frequency of the signal",
                        null=True,
                    ),
                ),
                (
                    "median_frequency",
                    models.IntegerField(
                        blank=True,
                        help_text="[Hz] The frequency at which half of the frequencies of the whistle contour lie above and half of the frequencies of the whistle contour lie below",
                        null=True,
                    ),
                ),
                (
                    "beginning_sweep_slope",
                    models.FloatField(
                        blank=True,
                        help_text="Slope at the beginning of the signal",
                        null=True,
                    ),
                ),
                (
                    "end_sweep_slope",
                    models.FloatField(
                        blank=True,
                        help_text="Slope at the end of the signal",
                        null=True,
                    ),
                ),
                (
                    "steps_count",
                    models.IntegerField(
                        blank=True, help_text="Number of steps in the signal", null=True
                    ),
                ),
                (
                    "relative_peaks_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of relative minimum/maximum frequency in the signal",
                        null=True,
                    ),
                ),
                (
                    "has_harmonics",
                    models.BooleanField(
                        blank=True, help_text="If the signal has harmonics", null=True
                    ),
                ),
                (
                    "harmonics_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of harmonics in the signal",
                        null=True,
                    ),
                ),
                (
                    "level_peak_frequency",
                    models.FloatField(
                        blank=True,
                        help_text="[Hz] The frequency at which the maximum level in the signal occurs",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="[s] Duration of the signal", null=True
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLAT", "Flat"),
                            ("ASC", "Ascending"),
                            ("DESC", "Descending"),
                            ("MOD", "Modulated"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationresult",
            name="acoustic_features",
            field=models.OneToOneField(
                blank=True,
                help_text="Acoustic features add a better description to the signal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotation_result",
                to="api.annotationresultacousticfeatures",
            ),
        ),
    ]
