# Generated by Django 3.2.25 on 2025-02-14 08:06

import django.core.validators
from django.db import migrations, models

from backend.api.models import AnnotationFileRange, DatasetFile


def add_limit_ids(apps, schema_editor):
    model: AnnotationFileRange = apps.get_model("api", "AnnotationFileRange")
    model_file: DatasetFile = apps.get_model("api", "DatasetFile")
    for r in model.objects.all():
        files = model_file.objects.filter(
            dataset_id__in=r.annotation_campaign.datasets.values_list("id", flat=True)
        ).order_by("start", "id")
        r.first_file_id = files[r.first_file_index].id
        r.last_file_id = files[r.last_file_index].id
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_confidence_set_indicator_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationfilerange",
            name="first_file_id",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="annotationfilerange",
            name="last_file_id",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.RunPython(add_limit_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="first_file_id",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="last_file_id",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
