# Generated by Django 3.2.25 on 2025-02-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_file_range_limits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasetfile",
            options={"ordering": ("start", "id")},
        ),
    ]
