# Generated by Django 3.2.25 on 2025-01-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_auto_20241216_1657"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="confidenceindicator",
            table=None,
        ),
        migrations.AlterModelTable(
            name="confidenceindicatorset",
            table=None,
        ),
    ]
