# Generated by Django 3.2.25 on 2025-01-29 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_alter_confidenceindicator_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="beginning_sweep_slope",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="end_sweep_slope",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="harmonics_count",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="level_peak_frequency",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="max_frequency",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="median_frequency",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="min_frequency",
        ),
        migrations.RemoveField(
            model_name="annotationresultacousticfeatures",
            name="relative_peaks_count",
        ),
        migrations.AddField(
            model_name="annotationresultacousticfeatures",
            name="relative_max_frequency_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of relative maximum frequency in the signal",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="annotationresultacousticfeatures",
            name="relative_min_frequency_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of relative minimum frequency in the signal",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="annotationresultacousticfeatures",
            name="steps_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of steps (flat segment) in the signal",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
