# Generated by Django 3.2.25 on 2025-02-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_confidence_set_indicator_relation"),
        ("api", "0068_final_acoustic_features"),
    ]

    operations = []
