# Generated by Django 3.2.25 on 2025-02-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_alter_datasetfile_options"),
        ("api", "0070_merge_0066_file_range_limits_0069_merge_20250213_1409"),
    ]

    operations = []
