# Generated by Django 3.2.25 on 2025-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_merge_20250218_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationresult",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[("W", "Weak"), ("P", "Point"), ("B", "Box")],
                help_text="Type of the annotation",
                null=True,
            ),
        ),
        migrations.RunSQL(
            """
                UPDATE annotation_results r
                SET type = 'W',
                    start_time=null,
                    end_time=null,
                    start_frequency=null,
                    end_frequency=null
                FROM dataset_files f
                LEFT JOIN datasets d on f.dataset_id = d.id
                LEFT JOIN audio_metadata a on d.audio_metadatum_id = a.id
                WHERE f.id = r.dataset_file_id and
                     (
                        (
                            r.start_time isnull or
                            r.end_time isnull or
                            r.start_frequency isnull or
                            r.end_frequency isnull
                        ) or
                        (
                            r.start_time = 0 and
                            r.end_time = EXTRACT(EPOCH from f."end" - f.start) and
                            r.start_frequency = 0 and
                            r.end_frequency = a.dataset_sr / 2
                        )
                    );
          """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
                UPDATE annotation_results r
                SET type = 'B'
                WHERE type isnull;
          """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="annotationresult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("end_frequency__isnull", True),
                        ("end_time__isnull", True),
                        ("start_frequency__isnull", True),
                        ("start_time__isnull", True),
                        ("type", "W"),
                    ),
                    models.Q(
                        ("end_frequency__isnull", True),
                        ("end_time__isnull", True),
                        ("start_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "P"),
                    ),
                    models.Q(
                        ("end_frequency__isnull", False),
                        ("end_time__isnull", False),
                        ("start_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "B"),
                    ),
                    _connector="OR",
                ),
                name="Annotation type",
            ),
        ),
        migrations.AlterField(
            model_name="annotationresult",
            name="type",
            field=models.TextField(
                choices=[("W", "Weak"), ("P", "Point"), ("B", "Box")],
                help_text="Type of the annotation",
            ),
        ),
    ]
