# Generated by Django 3.2.25 on 2025-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_annotationresulttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="allow_point_annotation",
            field=models.BooleanField(default=False),
        ),
    ]
