# Generated by Django 3.2.25 on 2025-04-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_annotationresult_create_update_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationcampaign',
            name='label_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.labelset'),
        ),
    ]
