# Generated by Django 3.2.25 on 2025-07-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0002_link_to_bibliography"),
        ("api", "0081_alter_dataset_related_channel_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="metadatax_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ontology.label",
            ),
        ),
    ]
