# Generated by Django 3.2.25 on 2025-07-10 15:47

from django.db import migrations, models


class MigrationAction:
    def __init__(self, apps, _):
        self.AnnotationFileRange = apps.get_model("api", "AnnotationFileRange")
        self.DatasetFile = apps.get_model("api", "DatasetFile")

        for file_range in self.AnnotationFileRange.objects.all():
            self.migrate_file_range(file_range)

    def migrate_file_range(self, file_range):
        first_file = self.DatasetFile.objects.get(id=file_range.first_file_id)
        last_file = self.DatasetFile.objects.get(id=file_range.last_file_id)

        file_range.from_datetime = min(first_file.start, last_file.start)
        file_range.to_datetime = max(first_file.end, last_file.end)
        file_range.save()


class ReverseMigrationAction:
    def __init__(self, apps, _):
        self.AnnotationFileRange = apps.get_model("api", "AnnotationFileRange")
        self.DatasetFile = apps.get_model("api", "DatasetFile")

        for file_range in self.AnnotationFileRange.objects.all():
            self.migrate_file_range(file_range)

    def migrate_file_range(self, file_range):
        first_file = self.DatasetFile.objects.get(start=file_range.from_datetime)
        last_file = self.DatasetFile.objects.get(end=file_range.to_datetime)

        file_range.first_file_id = first_file.id
        file_range.last_file_id = last_file.id
        file_range.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_label_metadatax_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationfilerange",
            name="from_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotationfilerange",
            name="to_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(MigrationAction, ReverseMigrationAction),
        migrations.RemoveField(
            model_name="annotationfilerange",
            name="first_file_id",
        ),
        migrations.RemoveField(
            model_name="annotationfilerange",
            name="last_file_id",
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="from_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="annotationfilerange",
            name="to_datetime",
            field=models.DateTimeField(),
        ),
    ]
