# Generated by Django 3.2.25 on 2025-07-28 09:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_migrate_to_osekit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spectrogram',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', django.db.models.expressions.F('end'))), name='start is lower than end'),
        ),
    ]
