# Generated by Django 3.2.25 on 2025-07-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadatax', '0025_migrate_database'),
        ('api', '0084_migrate_to_osekit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='acoustic_features',
            field=models.OneToOneField(blank=True, help_text='Acoustic features add a better description to the signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation', to='api.acousticfeatures'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='detector_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.detectorconfiguration'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='spectrogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.spectrogram'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadatax.fileformat'),
        ),
    ]
