# Generated by Django 3.2.25 on 2025-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20250716_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationcampaign',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='annotationcampaign',
            name='instructions_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
