# Generated by Django 3.2.25 on 2025-07-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20250716_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelset',
            old_name='desc',
            new_name='description',
        ),
    ]
