"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# pylint: disable-next=line-too-long

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "backend.api.apps.ApiConfig",
    "backend.osmosewebsite.apps.OsmoseWebsiteConfig",
    "tinymce",
    "metadatax",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/backend/static/"
STATICFILES_DIRS = [BASE_DIR / "backend/api/static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
DATASET_IMPORT_FOLDER = Path("/opt/datawork/dataset")
DATASET_EXPORT_PATH = Path("datawork/dataset")  # linked to nginx conf
DATASET_FILES_FOLDER = Path("data/audio")
DATASET_SPECTRO_FOLDER = Path("processed/spectrogram")

FIELD_SPECTRO_CONFIG_NEEDED = [
    "nfft",
    "window_size",
    "overlap",
    "zoom_level",
    "desc",
    "spectro_normalization",
    "data_normalization",
    "zscore_duration",
    "hp_filter_min_freq",
    "colormap",
    "dynamic_min",
    "dynamic_max",
    "window_type",
    "frequency_resolution",
    "time_resolution_zoom_0",
    "time_resolution_zoom_1",
    "time_resolution_zoom_2",
    "time_resolution_zoom_3",
    "time_resolution_zoom_4",
    "time_resolution_zoom_5",
    "time_resolution_zoom_6",
    "time_resolution_zoom_7",
    "time_resolution_zoom_8",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django rest framework params
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "backend.osmosewebsite.pagination.OsmosePagination",
}

# rest_framework_simplejwt params
SIMPLE_JWT = {
    # TODO : return to a more conservative setting after implenting refresh in front
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8)
}

# Spectacular params for swagger-ui api documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "OSMOSE API",
    "DESCRIPTION": "Backend API for OSMOSE project meant to be used by the React frontend",
    # 'VERSION': '1.0.0',
}

# Fixtures location for testing
FIXTURE_DIRS = (
    BASE_DIR / "backend/tests/fixtures",
    BASE_DIR / "backend/osmosewebsite/tests/fixtures",
)

# TINYMCE Configuration
# https://www.tiny.cloud/docs/advanced/available-menu-items/

TINYMCE_COMPRESSOR = False
TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "plugins": "image, link, lists, media",
    "toolbar": "undo redo | formatselect blockquote | bold italic | alignleft aligncenter alignright alignjustify | bullist outdent indent | image | link unlink",
    "default_link_target": "_blank",
    "image_title": "true",
}
