fragment Comment on AnnotationCommentNode {
    id
    comment
}

query allAnnotationSpectrograms(
    $annotatorID: ID!
    $campaignID: ID!
    $phaseType: AnnotationPhaseType!

    # Pagination
    $limit: Int!
    $offset: Int!

    # Filtering
    $search: String
    $status: AnnotationTaskStatus
    $from: DateTime
    $to: DateTime

    $onlyAssigned: Boolean
    $withAnnotations: Boolean
    $annotationLabel: ID
    $annotationConfidence: ID
    $annotationDetector: ID
    $annotationAnnotator: ID
    $withAcousticFeatures: Boolean
) {
    allAnnotationSpectrograms(
        # Sort
        limit: $limit
        offset: $offset
        orderBy: "start"

        # Only assigned
        annotator: $annotatorID
        annotationCampaign: $campaignID
        phase: $phaseType
        onlyAssigned: $onlyAssigned

        # Search
        filename_Icontains: $search

        # Dates filters
        end_Gte: $from
        start_Lte: $to

        # Task filters
        annotationTasks_Status: $status

        # Annotation filters
        annotations_Exists: $withAnnotations
        annotations_Label: $annotationLabel
        annotations_Confidence: $annotationConfidence
        annotations_Detector: $annotationDetector
        annotations_Annotator: $annotationAnnotator
        annotations_AcousticFeatures_Exists: $withAcousticFeatures
    ) {
        resumeSpectrogramId(phase: $phaseType, campaignId: $campaignID)
        results {
            id
            filename
            start
            duration
            isAssigned(campaignId: $campaignID, phase: $phaseType)

            task(
                phase: $phaseType
                campaignId: $campaignID
            ) {
                status

                userAnnotations(
                    annotator: $annotationAnnotator
                    label: $annotationLabel
                    confidence: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }
                annotationsToCheck(
                    annotator: $annotationAnnotator
                    isUpdated: false # Since I need the count, if it is updated it will be counted on 'userAnnotation'
                    label: $annotationLabel
                    confidence: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }

                validAnnotationsToCheck: annotationsToCheck(
                    annotator: $annotationAnnotator
                    isValidatedBy: $annotatorID
                    label: $annotationLabel
                    confidence: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }
            }
        }
        totalCount
    }
}

query getAnnotationSpectrogram(
    $spectrogramID: ID!
    $annotatorID: ID!
    $campaignID: ID!
    $phaseType: AnnotationPhaseType!

    # Filtering
    $search: String
    $status: AnnotationTaskStatus
    $from: DateTime
    $to: DateTime

    $onlyAssigned: Boolean
    $withAnnotations: Boolean
    $annotationLabel: ID
    $annotationConfidence: ID
    $annotationDetector: ID
    $annotationAnnotator: ID
    $withAcousticFeatures: Boolean
) {
    annotationSpectrogramById(id: $spectrogramID) {
        id
        filename
        start
        duration

        isAssigned(phase: $phaseType, campaignId: $campaignID)

        task(
            phase: $phaseType
            campaignId: $campaignID
        ) {
            status

            userComments(
                author: $annotatorID,
                annotationPhase_Phase: $phaseType
            ) {
                results { ... Comment }
            }

            userAnnotations {
                results {
                    id
                    annotationPhase {
                        id
                    }
                    type
                    startTime
                    endTime
                    startFrequency
                    endFrequency
                    label {
                        name
                    }
                    confidence {
                        label
                    }
                    detectorConfiguration {
                        id
                        detector {
                            id
                            name
                        }
                    }
                    annotator {
                        id,
                        displayName
                    }
                    comments(author: $annotatorID) {
                        results { ... Comment }
                    }
                    validations(annotator: $annotatorID) {
                        results {
                            id
                            isValid
                        }
                    }
                    isUpdateOf {
                        id
                    }
                    acousticFeatures {
                        id
                        isIntensityTooLow
                        doesOverlapOtherSignals
                        startFrequency
                        endFrequency
                        relativeMinFrequencyCount
                        relativeMaxFrequencyCount
                        stepsCount
                        hasHarmonics
                        trend
                        hasSidebands
                        hasSubharmonics
                        hasFrequencyJumps
                        frequencyJumpsCount
                        hasDeterministicChaos
                    }
                }
            }
            annotationsToCheck {
                results {
                    id
                    annotationPhase {
                        id
                    }
                    type
                    startTime
                    endTime
                    startFrequency
                    endFrequency
                    label {
                        name
                    }
                    confidence {
                        label
                    }
                    detectorConfiguration {
                        id
                        detector {
                            id
                            name
                        }
                    }
                    annotator {
                        id,
                        displayName
                    }
                    comments(author: $annotatorID) {
                        results { ... Comment }
                    }
                    validations(annotator: $annotatorID) {
                        results {
                            id
                            isValid
                        }
                    }
                    isUpdateOf {
                        id
                    }
                    acousticFeatures {
                        id
                        isIntensityTooLow
                        doesOverlapOtherSignals
                        startFrequency
                        endFrequency
                        relativeMinFrequencyCount
                        relativeMaxFrequencyCount
                        stepsCount
                        hasHarmonics
                        trend
                        hasSidebands
                        hasSubharmonics
                        hasFrequencyJumps
                        frequencyJumpsCount
                        hasDeterministicChaos
                    }
                }
            }
        }
    }

    allAnnotationSpectrograms(
        # Sort
        orderBy: "start"

        # Only assigned
        annotator: $annotatorID
        annotationCampaign: $campaignID
        phase: $phaseType
        onlyAssigned: $onlyAssigned

        # Search
        filename_Icontains: $search

        # Dates filters
        end_Gte: $from
        start_Lte: $to

        # Task filters
        annotationTasks_Status: $status

        # Annotation filters
        annotations_Exists: $withAnnotations
        annotations_Label: $annotationLabel
        annotations_Confidence: $annotationConfidence
        annotations_Detector: $annotationDetector
        annotations_Annotator: $annotationAnnotator
        annotations_AcousticFeatures_Exists: $withAcousticFeatures
    ) {
        currentIndex(spectrogramId: $spectrogramID)
        totalCount
        previousSpectrogramId(spectrogramId: $spectrogramID)
        nextSpectrogramId(spectrogramId: $spectrogramID)
    }
}

query getAnnotationSpectrogramPaths(
    $spectrogramID: ID!
    $analysisID: ID!
) {
    spectrogramPaths(spectrogramId: $spectrogramID, analysisId: $analysisID) {
        audioPath
        spectrogramPath
    }
}

