export type Dataset = {
  id: string,
  name: string,
  type: string,
  folder_name: string,
  conf_folder: string,
  dataset_type_name: string,
  dataset_type_desc: string,
  files_type: string,
  files_count: number,
  location_name: string,
  location_desc: string,
  location_lat: string,
  location_lon: string,
  start_date: string,
  end_date: string,
  created_at: string,
};