# Generated by Django 3.2.23 on 2023-11-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('picture', models.URLField()),
                ('mailAddress', models.EmailField(max_length=254)),
                ('researchGateURL', models.URLField()),
                ('personalWebsiteURL', models.URLField()),
                ('githubURL', models.URLField()),
                ('linkedinURL', models.URLField()),
            ],
        ),
    ]
