# Generated by Django 3.2.23 on 2023-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="githubURL",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="linkedinURL",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="personalWebsiteURL",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="researchGateURL",
            field=models.URLField(null=True),
        ),
    ]
