# Generated by Django 3.2.23 on 2023-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0004_auto_20231124_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sorting level"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="isFormerMember",
            field=models.BooleanField(default=False, verbose_name="Is former member"),
        ),
    ]
