# Generated by Django 3.2.23 on 2023-11-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0005_auto_20231127_1508"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["level"]},
        ),
    ]
