# Generated by Django 3.2.23 on 2023-11-30 15:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0006_alter_teammember_options"),
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("body", tinymce.models.HTMLField()),
                ("date", models.DateField(blank=True, null=True)),
                ("vignette", models.URLField(default="")),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-date"],
            },
        ),
        migrations.RunSQL(
            """
            INSERT INTO osmosewebsite_news (id, title, intro, body, date, vignette)
            SELECT * FROM news
        """
        ),
    ]
