# Generated by Django 3.2.23 on 2023-12-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0006_alter_teammember_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="githubURL",
            new_name="github_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="isFormerMember",
            new_name="is_former_member",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="linkedinURL",
            new_name="linkedin_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="mailAddress",
            new_name="mail_address",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="personalWebsiteURL",
            new_name="personal_website_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="researchGateURL",
            new_name="research_gate_url",
        ),
    ]
