# Generated by Django 3.2.23 on 2024-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0007_auto_20231206_0954"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="name",
            new_name="firstname",
        ),
        migrations.AddField(
            model_name="teammember",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
