# Generated by Django 3.2.23 on 2023-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0008_auto_20231130_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="osmose_member_authors",
            field=models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
        ),
    ]
