# Generated by Django 3.2.23 on 2023-12-05 15:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0009_alter_news_osmose_member_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sorting level"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("thumbnail", models.URLField()),
                ("show_on_home_page", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("body", tinymce.models.HTMLField()),
                ("vignette", models.URLField(default="")),
                (
                    "contact",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
            ],
            options={
                "ordering": ["-end"],
            },
        ),
    ]
