# Generated by Django 3.2.23 on 2023-12-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0007_auto_20231206_0954"),
        ("osmosewebsite", "0009_alter_news_osmose_member_authors"),
    ]

    operations = []
