# Generated by Django 3.2.23 on 2023-12-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0010_merge_20231206_1102"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="vignette",
            new_name="thumbnail",
        ),
    ]
