# Generated by Django 3.2.23 on 2023-12-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0010_collaborator_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="vignette",
            new_name="thumbnail",
        ),
    ]
