# Generated by Django 3.2.23 on 2023-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0011_rename_vignette_project_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(blank=True, to="osmosewebsite.Collaborator"),
        ),
    ]
