# Generated by Django 3.2.23 on 2024-01-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0008_auto_20240103_1132"),
        ("osmosewebsite", "0011_rename_vignette_news_thumbnail"),
    ]

    operations = []
