# Generated by Django 3.2.23 on 2023-12-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0011_rename_vignette_news_thumbnail"),
        ("osmosewebsite", "0013_collaborator_url"),
    ]

    operations = []
