# Generated by Django 3.2.23 on 2024-01-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0012_merge_20240108_1138"),
        ("osmosewebsite", "0014_merge_20231206_1444"),
    ]

    operations = []
