# Generated by Django 3.2.23 on 2024-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0016_alter_teammember_mail_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
