# Generated by Django 3.2.23 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0017_alter_teammember_biography"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaborator",
            options={"ordering": ["level", "name"]},
        ),
    ]
