# Generated by Django 3.2.23 on 2024-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmosewebsite', '0018_alter_collaborator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='show_on_presentation_page',
            field=models.BooleanField(default=False),
        ),
    ]
