# Generated by Django 3.2.23 on 2024-05-23 08:18

import django.contrib.postgres.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0019_collaborator_show_on_aplose_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("thumbnail", models.URLField(default="")),
                (
                    "other_authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "osmose_member_authors",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
            ],
            options={
                "verbose_name_plural": "trap",
                "ordering": ["-date"],
            },
        ),
    ]
