# Generated by Django 3.2.25 on 2024-08-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0019_collaborator_show_on_aplose_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("presenter_name", models.CharField(max_length=255)),
                ("intro", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("thumbnail", models.URLField(default="")),
                ("presenter_linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "presenter_mail_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "presenter_research_gate_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Research Gate URL"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "trap",
                "ordering": ["-date"],
            },
        ),
    ]
