# Generated by Django 3.2.23 on 2024-07-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0020_trap"),
    ]

    operations = [
        migrations.AddField(
            model_name="trap",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trap",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
