# Generated by Django 3.2.25 on 2024-09-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0020_trap"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Trap",
            new_name="ScientificTalk",
        ),
        migrations.AlterModelOptions(
            name="scientifictalk",
            options={"ordering": ["-date"]},
        ),
    ]
