# Generated by Django 3.2.23 on 2024-07-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0021_auto_20240702_1039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trap",
            options={},
        ),
    ]
