# Generated by Django 3.2.23 on 2024-07-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0022_alter_trap_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trap",
            old_name="linkedin",
            new_name="linkedin_url",
        ),
        migrations.RenameField(
            model_name="trap",
            old_name="mail",
            new_name="mail_address",
        ),
    ]
