# Generated by Django 3.2.25 on 2024-11-21 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0022_project_metadatax_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="contact",
            new_name="osmose_member_contacts",
        ),
        migrations.AddField(
            model_name="project",
            name="other_contacts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
