# Generated by Django 3.2.25 on 2024-11-21 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0023_project_contact"),
    ]

    operations = [
        # Enable reverse migration
        migrations.AlterField(
            model_name="scientifictalk",
            name="presenter_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, default="Default"
            ),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="scientifictalk",
            name="presenter_linkedin_url",
        ),
        migrations.RemoveField(
            model_name="scientifictalk",
            name="presenter_mail_address",
        ),
        migrations.RemoveField(
            model_name="scientifictalk",
            name="presenter_name",
        ),
        migrations.RemoveField(
            model_name="scientifictalk",
            name="presenter_research_gate_url",
        ),
        # Add new fields
        migrations.AddField(
            model_name="scientifictalk",
            name="osmose_member_presenters",
            field=models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
        ),
        migrations.AddField(
            model_name="scientifictalk",
            name="other_presenters",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
