# Generated by Django 3.2.23 on 2024-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0023_auto_20240702_1414"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trap",
            name="other_authors",
        ),
        migrations.AddField(
            model_name="trap",
            name="research_gate_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Research Gate URL"
            ),
        ),
    ]
