# Generated by Django 3.2.25 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0024_scientifictalks_presenters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scientifictalk",
            name="intro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
