# Generated by Django 3.2.23 on 2024-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0024_auto_20240702_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="trap",
            name="firstname",
            field=models.CharField(default="DefaultFirstName", max_length=100),
        ),
        migrations.AddField(
            model_name="trap",
            name="lastname",
            field=models.CharField(
                blank=True, default="DefaultFirstName", max_length=100, null=True
            ),
        ),
    ]
