# Generated by Django 3.2.23 on 2024-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0025_auto_20240703_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trap",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
