# Generated by Django 3.2.25 on 2025-05-28 09:50

import django.utils.timezone
from django.db import migrations, models


def create_scientist(apps, schema_editor):
    team_member_model = apps.get_model("osmosewebsite", "TeamMember")
    scientist_model = apps.get_model("osmosewebsite", "Scientist")
    institution_model = apps.get_model("osmosewebsite", "Institution")

    institution = institution_model.objects.create(
        name="Default",
        city="Default",
        country="Default",
    )

    for member in team_member_model.objects.all():
        member.scientist = scientist_model.objects.create(
            first_name=member.firstname,
            last_name=member.lastname,
        )
        member.scientist.institutions.add(institution)
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0025_alter_scientifictalk_intro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Scientist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "institutions",
                    models.ManyToManyField(
                        related_name="scientists", to="osmosewebsite.Institution"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teammember",
            name="scientist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_members",
                to="osmosewebsite.scientist",
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(create_scientist, migrations.RunPython.noop),
    ]
