# Generated by Django 3.2.25 on 2025-05-28 09:50

import django.utils.timezone
from django.db import migrations, models


def remove_scientist(apps, schema_editor):
    team_member_model = apps.get_model("osmosewebsite", "TeamMember")

    for member in team_member_model.objects.all():
        member.firstname = member.scientist.first_name
        member.lastname = member.scientist.last_name
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0026_add_scientist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="firstname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=remove_scientist),
        migrations.RemoveField(
            model_name="teammember",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="scientist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_members",
                to="osmosewebsite.scientist",
            ),
        ),
    ]
