# Generated by Django 3.2.25 on 2025-05-28 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0026_add_scientist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="scientist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_members",
                to="osmosewebsite.scientist",
            ),
        ),
    ]
