# Generated by Django 3.2.23 on 2024-07-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0027_remove_trap_osmose_member_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trap",
            old_name="firstname",
            new_name="firstname_presenter",
        ),
        migrations.RenameField(
            model_name="trap",
            old_name="lastname",
            new_name="lastname_presenter",
        ),
        migrations.RenameField(
            model_name="trap",
            old_name="linkedin_url",
            new_name="linkedin_url_presenter",
        ),
    ]
