# Generated by Django 3.2.25 on 2025-05-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmosewebsite', '0029_add_bibliography_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scientist',
            unique_together={('first_name', 'last_name')},
        ),
    ]
