# Generated by Django 3.2.25 on 2025-05-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmosewebsite', '0030_add_scientist_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='scientist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='team_member', to='osmosewebsite.scientist'),
        ),
    ]
