# Generated by Django 3.2.25 on 2025-06-03 09:35

from django.db import migrations, models
from django.db.models import Q


def update_publication_status(apps, schema_editor):
    bibliography_model = apps.get_model("osmosewebsite", "Bibliography")
    bibliography_model.objects.filter(~Q(publication_status="P")).update(
        publication_status="U"
    )


def reverse_update_publication_status(apps, schema_editor):
    bibliography_model = apps.get_model("osmosewebsite", "Bibliography")
    bibliography_model.objects.filter(~Q(publication_status="P")).update(
        publication_status="D"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0031_alter_teammember_scientist"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliography",
            name="conference_abstract_book_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bibliography",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("R", "In Review"),
                    ("U", "Upcoming"),
                    ("P", "Published"),
                ],
                max_length=1,
            ),
        ),
        migrations.RunPython(
            update_publication_status, reverse_code=reverse_update_publication_status
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_status",
            field=models.CharField(
                choices=[("U", "Upcoming"), ("P", "Published")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "Software"),
                    ("A", "Article"),
                    ("C", "Conference"),
                    ("P", "Poster"),
                ],
                max_length=1,
            ),
        ),
    ]
