# Generated by Django 3.2.25 on 2025-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0003_auto_20250630_1401'),
        ('osmosewebsite', '0032_update_bibliography_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='metadatax_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_project', to='acquisition.project'),
        ),
    ]
