# Generated by Django 3.2.25 on 2025-02-20 14:48

from django.db import migrations, models

from backend.aplose.models.user import Datawork, AploseUser


def create_datawork_and_assign(apps, schema_editor):
    datawork_model: Datawork = apps.get_model("aplose", "Datawork")
    base_datawork = datawork_model.objects.create(name="Base", folder_name="datawork")
    aplose_user_model: AploseUser = apps.get_model("aplose", "AploseUser")
    for user in aplose_user_model.objects.all():
        user.allowed_datawork.add(base_datawork)


class Migration(migrations.Migration):

    dependencies = [
        ("aplose", "0001_aplose_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datawork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("folder_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="aploseuser",
            name="allowed_datawork",
            field=models.ManyToManyField(
                related_name="allowed_users", to="aplose.Datawork"
            ),
        ),
        migrations.RunPython(
            create_datawork_and_assign, reverse_code=migrations.RunPython.noop
        ),
    ]
