# Generated by Django 3.2.25 on 2025-03-04 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aplose", "0001_aplose_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "annotators",
                    models.ManyToManyField(
                        related_name="annotator_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
